CREATE TABLE IF NOT EXISTS dbs (
  id INTEGER PRIMARY KEY, 
  name VARCHAR NOT NULL UNIQUE, 
  path VARCHAR NOT NULL,
  root VARCHAR NOT NULL,
  app_created INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS current_db (
    id INTEGER PRIMARY KEY,
    current_db TEXT NOT NULL
);