// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDB(arg1:main.CreateDBRequest):Promise<main.Result>;

export function GetCurrentDB():Promise<main.Result>;

export function GetNavData():Promise<main.Result>;

export function Query(arg1:main.QueryRequest):Promise<main.Result>;

export function SetCurrentDB(arg1:string):Promise<main.Result>;

export function UpdateDB(arg1:main.UpdateRequest):Promise<main.Result>;
