// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDB(arg1) {
  return window['go']['main']['App']['CreateDB'](arg1);
}

export function GetCurrentDB() {
  return window['go']['main']['App']['GetCurrentDB']();
}

export function GetNavData() {
  return window['go']['main']['App']['GetNavData']();
}

export function GetRootPath() {
  return window['go']['main']['App']['GetRootPath']();
}

export function OpenFolderOnStart() {
  return window['go']['main']['App']['OpenFolderOnStart']();
}

export function Query(arg1) {
  return window['go']['main']['App']['Query'](arg1);
}

export function QueryAll(arg1) {
  return window['go']['main']['App']['QueryAll'](arg1);
}

export function RemoveDB(arg1) {
  return window['go']['main']['App']['RemoveDB'](arg1);
}

export function SetCurrentDB(arg1) {
  return window['go']['main']['App']['SetCurrentDB'](arg1);
}

export function SetupMain() {
  return window['go']['main']['App']['SetupMain']();
}

export function UpdateDB(arg1) {
  return window['go']['main']['App']['UpdateDB'](arg1);
}
