// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateDB(arg1:main.CreateDBRequest):Promise<main.AppResult>;

export function GetCurrentDB():Promise<main.AppResult>;

export function GetNavData():Promise<main.AppResult>;

export function GetRootPath():Promise<main.AppResult>;

export function OpenFolderOnStart():Promise<main.AppResult>;

export function Query(arg1:main.QueryRequest):Promise<main.AppResult>;

export function QueryAll(arg1:string):Promise<main.AppResult>;

export function RemoveDB(arg1:string):Promise<main.AppResult>;

export function SetCurrentDB(arg1:string):Promise<main.AppResult>;

export function SetupMain():Promise<main.AppResult>;

export function UpdateDB(arg1:main.UpdateRequest):Promise<main.AppResult>;
